### PR TITLE
fixing "ImportError" in the 6 lines and 7

### PR DESCRIPTION
**Pull request by EmadDeve20**
hi Chris Amico.
I Using GNU/Linux os And in GNU/Linux, I can not run the cli.py file. But with a small change I made, this problem was solved. If you like, please merging.

### CODE REVIEW

**Comment by eyeseast** [comment]
Hi @EmadDeve20. What version of Python are you using?

**Comment by EmadDeve20** [comment]
hi, and I using python 3.8 and you can see this message:

Screenshot from 2020-09-29 01-33-30

**Comment by eyeseast** [comment]
This change makes the tests (and imports in general) fail:

```python
In [1]: import geocode_sqlite.cli
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-37e464a0e67e> in <module>
----> 1 import geocode_sqlite.cli

~/code/geocode-sqlite/geocode_sqlite/cli.py in <module>
      4 from sqlite_utils import Database
      5 
----> 6 from utils import geocode_table
      7 from testing import DummyGeocoder
      8 

ModuleNotFoundError: No module named 'utils'
```

If you want to import the `cli` module, do `import geocode_sqlite.cli` or `from geocode_sqlite import cli`.

**Comment by EmadDeve20** [comment]
Oh yes, this is better, and thank you for teaching me.
Good luck :D

**Pull request closed without merging**
